version: "3"


services:

  app:

    build:
      context: ./src
      dockerfile: Dockerfile 

    env_file:
      - .env

    environment:
      - NEF_IP=${NEF_IP}
      - NEF_PORT=${NEF_PORT}
      - NEF_USER=${NEF_USER}
      - NEF_PASS=${NEF_PASS}
      - PATH_TO_CERTS=${PATH_TO_CERTS}
      - CAPIF_HOSTNAME=${CAPIF_HOSTNAME}
      - CAPIF_PORT=${CAPIF_PORT}
      - CAPIF_PORT_HTTPS=${CAPIF_PORT_HTTPS}
      - CAPIF_IP=${CAPIF_IP}
      - NEF_CALLBACK_IP=${NEF_CALLBACK_IP}
      - NEF_CALLBACK_PORT=${NEF_CALLBACK_PORT}

    container_name: zorte_netapp

    extra_hosts:
      - capifcore:${CAPIF_IP}
    ports:
      - "5000:5000"
      
  influxdb:
    image: influxdb:1.8-alpine
    ports:
      - '8086:8086'

    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin

    container_name: influxdb