version: "3"


services:

  app:
    build: .

    env_file:
      - .env

    container_name: zorte_netapp

    extra_hosts:
      - host.docker.internal:host-gateway
      - capifcore:${CAPIF_IP}
    ports:
      - "5000:5000"
      
