version: "3"


services:

  app:

    build:
      context: ./src
      dockerfile: Dockerfile 

    env_file:
      - .env

    container_name: zorte_netapp

    extra_hosts:
      - capifcore:${CAPIF_IP}
    ports:
      - "5000:5000"
   

  grafana:
    build:
      context: "./grafana-svc"
      dockerfile: Dockerfile
    container_name: grafana

    extra_hosts:
      - influxdb:${INFLUX_IP}

    ports:
      - "3000:3000"

  influxdb:
    image: influxdb:1.8-alpine
    ports:
      - '8086:8086'

    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin

    container_name: influxdb