version: "3.9"


services:

  app:
    build: .
    environment:
      - NEF_ADDRESS=${NEF_ADDRESS}
      - NEF_USER=${NEF_USER}
      - NEF_PASSWORD=${NEF_PASSWORD}
      - PATH_TO_CERTS=${PATH_TO_CERTS}
      - CAPIF_HOSTNAME=${CAPIF_HOSTNAME}
      - CAPIF_PORT_HTTP=${CAPIF_PORT_HTTP}
      - CAPIF_PORT_HTTPS=${CAPIF_PORT_HTTPS}
      - CALLBACK_ADDRESS=${CALLBACK_ADDRESS}

    container_name: zorte_netapp

    extra_hosts:
      - capifcore:${CAPIF_IP}
    ports:
      - "5000:5000"
    #volumes:
    #  - ./src/api.py:/zortenet_netapp/api.py
    #  - ./src/netapp_utils.py:/zortenet_netapp/netapp_utils.py
    #  - ./src/prepare.sh:/zortenet_netapp/prepare.sh
    #  - ./src/capif_registration_template.json:/zortenet_netapp/capif_registration_template.json
      