version: "3.9"


services:

  app:
    build: .
    environment:
      - nef_url=${nef_url}
      - nef_port=${nef_port}
      - nef_user=${nef_user}
      - nef_pass=${nef_pass}
      - netapp_host=${netapp_host}
      - netapp_ip=${netapp_ip}
      - netapp_port=${netapp_port}



    container_name: zorte_netapp
    networks:
      - nef_emulator_services_default
    ports:
      - "5001:5000"
    volumes:
      - ./src/api.py:/zortenet_netapp/api.py

    command: python -u /zortenet_netapp/api.py


networks:
  nef_emulator_services_default:
    external: true
