{
 "title": "monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "device",
    "label": "device",
    "query": "show tag values from \"autogen\".\"devices\" with key =\"device\""
   }
  ]
 },
 "panels": [
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"percent\"  FROM \"autogen\".\"ram\" WHERE  (\"device\"::tag =~ /$device/ )\n"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"percent\"  FROM \"autogen\".\"cpu\" WHERE (\"device\"::tag =~ /$device/ )\n"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mibits" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network",
     "query": "SELECT  derivative(mean(\"bytes_sent\"),10s) / 8000  AS Output FROM \"autogen\".\"network\" WHERE  (\"device\"::tag =~ /$device/ ) AND $timeFilter GROUP BY time($interval) fill(none)",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$device$/" }
     ]
    },
    {
     "query": "SELECT  derivative(mean(\"bytes_recv\"),10s)/8000 AS Input FROM \"autogen\".\"network\" WHERE  (\"device\"::tag =~ /$device/ )AND $timeFilter GROUP BY time($interval) fill(none)\n"
    }
   ]
  },
  {
   "title": "Alerts And Operation Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nef_qos",
     "query": "SELECT \"event\" ,\"status\" FROM \"alerts\"  ORDER BY desc LIMIT 10",
     "select": [
      [
       { "params": [ "event" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "camera_controler" }
     ]
    }
   ]
  },
  {
   "title": "NEF QoS Monitoring",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "query": "SELECT \"event\" FROM \"autogen\".\"nef_qos\"  WHERE  (\"device\"::tag =~ /$device/ )  ORDER BY desc LIMIT 10"
    }
   ]
  }
 ]
}